version: "3.9"

services:
  db:
    build: .
    container_name: db
    environment:
      POSTGRES_USER: missions_user
      POSTGRES_PASSWORD: pg123
      POSTGRES_DB: missions_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "missions_user", "-d", "missions_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - airnet
    restart: unless-stopped

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      DATA_SOURCE_NAME: "postgresql://missions_user:pg123@db:5432/missions_db?sslmode=disable"
    command:
      - "--extend.query-path=/etc/postgres-queries.yml"
    volumes:
      - ./graphs/postgres-queries.yml:/etc/postgres-queries.yml
    depends_on:
      - db
    ports:
      - "9187:9187"
    networks:
      - airnet

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./graphs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./graphs/prometheus-recording.rules.yml:/etc/prometheus/recording.rules.yml
      # - ./graphs/postgres-alerts.yml:/etc/prometheus/alerts.yml
    depends_on:
      - postgres_exporter
    ports:
      - "9090:9090"
    networks:
      - airnet

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./graphs/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/postgres-dashboard.json
      - ./graphs/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./graphs/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - airnet


networks:
  airnet:
    driver: bridge

volumes:
  postgres_data:
